# fly.toml для MindFlow Telegram Bot

app = "mindflow-bot"
primary_region = "fra"

[build]

[[services]]
  internal_port = 3000
  protocol = "tcp"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
