services:
  - type: web
    name: mindflow-bot
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: API_URL
        sync: false
      - key: WEB_APP_URL
        sync: false
